### ISSUE TITLE
Remote Backup

### ISSUE THREAD

**Issue by apographon** [nicokaiser/rpi-camera-import#4]
While using a WLAN connection, why not pushing the pictures via SFTP/FTP/WebDav/.... to any remote destination?

**Comment by nicokaiser** [comment]
The idea was to build a tool that enables you to back up photos when there is no network (and even maybe no electricity) available.

But of course, you can use this to build a more sophisticated appliance that e.g. rsyncs the `~/Pictures` folder to another destination or uses something like Resilio Sync to sync files in the background.

This however would require the device to permanently mount its partitions in RW, so you need to cleanly shut down before switching off...
